# Generated by Django 2.1.5 on 2019-01-12 23:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('anyone')),)), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='titulo',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
